version: '2' 

services:
        jupyter:
                image: jupyter/base-notebook:2c80cf3537ca
                ports:
                        - "8888:8888"
                volumes: 
                        - "./work:/home/jovyan/work/"
                command: start-notebook.sh --NotebookApp.token=''
