version: '2' 

services:
        jupyter:
                build: ./jupyter/
                ports:
                        - "8888:8888"
                volumes: 
                        - "./work:/home/jovyan/work/"
                command:
                        start-notebook.sh --NotebookApp.token=''
        mysql:
                image: mysql:5.7
                environment:
                        - MYSQL_ROOT_PASSWORD=iii
                        - MYSQL_USER=test
                        - MYSQL_PASSWORD=test
                        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
                ports:
                        - "3306:3306"
                expose:
                        - "3306" 
                container_name: mysql-1
